services:
  monolito-dev:
    image: maven:4.0.0-rc-4-amazoncorretto-21-debian
    container_name: zoolip-dev
    working_dir: /app
    ports:
      - "3050:3050"
      - "9010:9010"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/zoolip?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=2007absalom
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - spring_devtools_restart_additional-paths=src/main/java
    command: mvn -Dspring-boot.run.fork=false    spring-boot:run
    networks:
      - zoolip-net
  db:
    image: mysql:8.0-debian
    container_name: zoolip-db
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "2007absalom"
      MYSQL_DATABASE: "zoolip"
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p2007absalom" ]
      interval: 100s
      timeout: 100s
      retries: 10
      start_period: 100s
    restart: unless-stopped
    networks:
      - zoolip-net

  monolito:
    build: .
    container_name: zoolip
    ports:
      - "3050:3050"
      - "9010:9010"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/zoolip?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=2007absalom
    restart: unless-stopped
    networks:
      - zoolip-net
networks:
  zoolip-net:
    driver: bridge